package com.baselibrary.dao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.baselibrary.pojo.ArcMaleFace;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ARC_MALE_FACE".
*/
public class ArcMaleFaceDao extends AbstractDao<ArcMaleFace, Long> {

    public static final String TABLENAME = "ARC_MALE_FACE";

    /**
     * Properties of entity ArcMaleFace.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UId = new Property(0, Long.class, "uId", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property FaceFeature = new Property(2, byte[].class, "faceFeature", false, "FACE_FEATURE");
        public final static Property HeadImg = new Property(3, byte[].class, "headImg", false, "HEAD_IMG");
    }


    public ArcMaleFaceDao(DaoConfig config) {
        super(config);
    }
    
    public ArcMaleFaceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ARC_MALE_FACE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: uId
                "\"NAME\" TEXT," + // 1: name
                "\"FACE_FEATURE\" BLOB," + // 2: faceFeature
                "\"HEAD_IMG\" BLOB);"); // 3: headImg
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ARC_MALE_FACE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ArcMaleFace entity) {
        stmt.clearBindings();
 
        Long uId = entity.getUId();
        if (uId != null) {
            stmt.bindLong(1, uId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        byte[] faceFeature = entity.getFaceFeature();
        if (faceFeature != null) {
            stmt.bindBlob(3, faceFeature);
        }
 
        byte[] headImg = entity.getHeadImg();
        if (headImg != null) {
            stmt.bindBlob(4, headImg);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ArcMaleFace entity) {
        stmt.clearBindings();
 
        Long uId = entity.getUId();
        if (uId != null) {
            stmt.bindLong(1, uId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        byte[] faceFeature = entity.getFaceFeature();
        if (faceFeature != null) {
            stmt.bindBlob(3, faceFeature);
        }
 
        byte[] headImg = entity.getHeadImg();
        if (headImg != null) {
            stmt.bindBlob(4, headImg);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ArcMaleFace readEntity(Cursor cursor, int offset) {
        ArcMaleFace entity = new ArcMaleFace( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // uId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2), // faceFeature
            cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3) // headImg
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ArcMaleFace entity, int offset) {
        entity.setUId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFaceFeature(cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2));
        entity.setHeadImg(cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ArcMaleFace entity, long rowId) {
        entity.setUId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ArcMaleFace entity) {
        if(entity != null) {
            return entity.getUId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ArcMaleFace entity) {
        return entity.getUId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
