package com.baselibrary.dao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.baselibrary.pojo.Face;
import com.baselibrary.pojo.IdCard;
import com.baselibrary.pojo.Pw;
import com.baselibrary.pojo.Student;
import com.baselibrary.pojo.User;

import com.baselibrary.dao.db.FaceDao;
import com.baselibrary.dao.db.IdCardDao;
import com.baselibrary.dao.db.PwDao;
import com.baselibrary.dao.db.StudentDao;
import com.baselibrary.dao.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig faceDaoConfig;
    private final DaoConfig idCardDaoConfig;
    private final DaoConfig pwDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig userDaoConfig;

    private final FaceDao faceDao;
    private final IdCardDao idCardDao;
    private final PwDao pwDao;
    private final StudentDao studentDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        faceDaoConfig = daoConfigMap.get(FaceDao.class).clone();
        faceDaoConfig.initIdentityScope(type);

        idCardDaoConfig = daoConfigMap.get(IdCardDao.class).clone();
        idCardDaoConfig.initIdentityScope(type);

        pwDaoConfig = daoConfigMap.get(PwDao.class).clone();
        pwDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        faceDao = new FaceDao(faceDaoConfig, this);
        idCardDao = new IdCardDao(idCardDaoConfig, this);
        pwDao = new PwDao(pwDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Face.class, faceDao);
        registerDao(IdCard.class, idCardDao);
        registerDao(Pw.class, pwDao);
        registerDao(Student.class, studentDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        faceDaoConfig.clearIdentityScope();
        idCardDaoConfig.clearIdentityScope();
        pwDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public FaceDao getFaceDao() {
        return faceDao;
    }

    public IdCardDao getIdCardDao() {
        return idCardDao;
    }

    public PwDao getPwDao() {
        return pwDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
