package com.baselibrary.dao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.baselibrary.pojo.Face;
import com.baselibrary.pojo.IdCard;
import com.baselibrary.pojo.Pw;
import com.baselibrary.pojo.Student;
import com.baselibrary.pojo.User;
import com.baselibrary.pojo.Finger3;
import com.baselibrary.pojo.Finger6;
import com.baselibrary.pojo.Manager;

import com.baselibrary.dao.db.FaceDao;
import com.baselibrary.dao.db.IdCardDao;
import com.baselibrary.dao.db.PwDao;
import com.baselibrary.dao.db.StudentDao;
import com.baselibrary.dao.db.UserDao;
import com.baselibrary.dao.db.Finger3Dao;
import com.baselibrary.dao.db.Finger6Dao;
import com.baselibrary.dao.db.ManagerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig faceDaoConfig;
    private final DaoConfig idCardDaoConfig;
    private final DaoConfig pwDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig finger3DaoConfig;
    private final DaoConfig finger6DaoConfig;
    private final DaoConfig managerDaoConfig;

    private final FaceDao faceDao;
    private final IdCardDao idCardDao;
    private final PwDao pwDao;
    private final StudentDao studentDao;
    private final UserDao userDao;
    private final Finger3Dao finger3Dao;
    private final Finger6Dao finger6Dao;
    private final ManagerDao managerDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        faceDaoConfig = daoConfigMap.get(FaceDao.class).clone();
        faceDaoConfig.initIdentityScope(type);

        idCardDaoConfig = daoConfigMap.get(IdCardDao.class).clone();
        idCardDaoConfig.initIdentityScope(type);

        pwDaoConfig = daoConfigMap.get(PwDao.class).clone();
        pwDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        finger3DaoConfig = daoConfigMap.get(Finger3Dao.class).clone();
        finger3DaoConfig.initIdentityScope(type);

        finger6DaoConfig = daoConfigMap.get(Finger6Dao.class).clone();
        finger6DaoConfig.initIdentityScope(type);

        managerDaoConfig = daoConfigMap.get(ManagerDao.class).clone();
        managerDaoConfig.initIdentityScope(type);

        faceDao = new FaceDao(faceDaoConfig, this);
        idCardDao = new IdCardDao(idCardDaoConfig, this);
        pwDao = new PwDao(pwDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        finger3Dao = new Finger3Dao(finger3DaoConfig, this);
        finger6Dao = new Finger6Dao(finger6DaoConfig, this);
        managerDao = new ManagerDao(managerDaoConfig, this);

        registerDao(Face.class, faceDao);
        registerDao(IdCard.class, idCardDao);
        registerDao(Pw.class, pwDao);
        registerDao(Student.class, studentDao);
        registerDao(User.class, userDao);
        registerDao(Finger3.class, finger3Dao);
        registerDao(Finger6.class, finger6Dao);
        registerDao(Manager.class, managerDao);
    }
    
    public void clear() {
        faceDaoConfig.clearIdentityScope();
        idCardDaoConfig.clearIdentityScope();
        pwDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        finger3DaoConfig.clearIdentityScope();
        finger6DaoConfig.clearIdentityScope();
        managerDaoConfig.clearIdentityScope();
    }

    public FaceDao getFaceDao() {
        return faceDao;
    }

    public IdCardDao getIdCardDao() {
        return idCardDao;
    }

    public PwDao getPwDao() {
        return pwDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public Finger3Dao getFinger3Dao() {
        return finger3Dao;
    }

    public Finger6Dao getFinger6Dao() {
        return finger6Dao;
    }

    public ManagerDao getManagerDao() {
        return managerDao;
    }

}
