package com.baselibrary.dao.db;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.baselibrary.pojo.Finger6;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FINGER6".
*/
public class Finger6Dao extends AbstractDao<Finger6, Long> {

    public static final String TABLENAME = "FINGER6";

    /**
     * Properties of entity Finger6.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property FingerId = new Property(0, Long.class, "fingerId", true, "_id");
        public final static Property UserId = new Property(1, Long.class, "userId", false, "USER_ID");
        public final static Property Finger6Feature = new Property(2, byte[].class, "finger6Feature", false, "fingerFeature");
    }

    private Query<Finger6> user_Finger6ListQuery;

    public Finger6Dao(DaoConfig config) {
        super(config);
    }
    
    public Finger6Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FINGER6\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: fingerId
                "\"USER_ID\" INTEGER," + // 1: userId
                "\"fingerFeature\" BLOB);"); // 2: finger6Feature
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FINGER6\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Finger6 entity) {
        stmt.clearBindings();
 
        Long fingerId = entity.getFingerId();
        if (fingerId != null) {
            stmt.bindLong(1, fingerId);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(2, userId);
        }
 
        byte[] finger6Feature = entity.getFinger6Feature();
        if (finger6Feature != null) {
            stmt.bindBlob(3, finger6Feature);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Finger6 entity) {
        stmt.clearBindings();
 
        Long fingerId = entity.getFingerId();
        if (fingerId != null) {
            stmt.bindLong(1, fingerId);
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(2, userId);
        }
 
        byte[] finger6Feature = entity.getFinger6Feature();
        if (finger6Feature != null) {
            stmt.bindBlob(3, finger6Feature);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Finger6 readEntity(Cursor cursor, int offset) {
        Finger6 entity = new Finger6( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // fingerId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2) // finger6Feature
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Finger6 entity, int offset) {
        entity.setFingerId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setFinger6Feature(cursor.isNull(offset + 2) ? null : cursor.getBlob(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Finger6 entity, long rowId) {
        entity.setFingerId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Finger6 entity) {
        if(entity != null) {
            return entity.getFingerId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Finger6 entity) {
        return entity.getFingerId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "finger6List" to-many relationship of User. */
    public List<Finger6> _queryUser_Finger6List(Long userId) {
        synchronized (this) {
            if (user_Finger6ListQuery == null) {
                QueryBuilder<Finger6> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UserId.eq(null));
                user_Finger6ListQuery = queryBuilder.build();
            }
        }
        Query<Finger6> query = user_Finger6ListQuery.forCurrentThread();
        query.setParameter(0, userId);
        return query.list();
    }

}
