package com.baselibrary.dao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.baselibrary.pojo.Pw;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PW".
*/
public class PwDao extends AbstractDao<Pw, Long> {

    public static final String TABLENAME = "PW";

    /**
     * Properties of entity Pw.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property PwId = new Property(0, Long.class, "pwId", true, "_id");
        public final static Property Password = new Property(1, String.class, "password", false, "password");
    }


    public PwDao(DaoConfig config) {
        super(config);
    }
    
    public PwDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PW\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: pwId
                "\"password\" TEXT);"); // 1: password
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PW\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Pw entity) {
        stmt.clearBindings();
 
        Long pwId = entity.getPwId();
        if (pwId != null) {
            stmt.bindLong(1, pwId);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(2, password);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Pw entity) {
        stmt.clearBindings();
 
        Long pwId = entity.getPwId();
        if (pwId != null) {
            stmt.bindLong(1, pwId);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(2, password);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Pw readEntity(Cursor cursor, int offset) {
        Pw entity = new Pw( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // pwId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // password
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Pw entity, int offset) {
        entity.setPwId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPassword(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Pw entity, long rowId) {
        entity.setPwId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Pw entity) {
        if(entity != null) {
            return entity.getPwId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Pw entity) {
        return entity.getPwId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
