package com.baselibrary.dao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.baselibrary.pojo.TestIdCard;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEST_ID_CARD".
*/
public class TestIdCardDao extends AbstractDao<TestIdCard, Long> {

    public static final String TABLENAME = "TEST_ID_CARD";

    /**
     * Properties of entity TestIdCard.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CardId = new Property(0, Long.class, "cardId", true, "_id");
        public final static Property CardNo = new Property(1, String.class, "cardNo", false, "CARD_NO");
    }


    public TestIdCardDao(DaoConfig config) {
        super(config);
    }
    
    public TestIdCardDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEST_ID_CARD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: cardId
                "\"CARD_NO\" TEXT);"); // 1: cardNo
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEST_ID_CARD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TestIdCard entity) {
        stmt.clearBindings();
 
        Long cardId = entity.getCardId();
        if (cardId != null) {
            stmt.bindLong(1, cardId);
        }
 
        String cardNo = entity.getCardNo();
        if (cardNo != null) {
            stmt.bindString(2, cardNo);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TestIdCard entity) {
        stmt.clearBindings();
 
        Long cardId = entity.getCardId();
        if (cardId != null) {
            stmt.bindLong(1, cardId);
        }
 
        String cardNo = entity.getCardNo();
        if (cardNo != null) {
            stmt.bindString(2, cardNo);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TestIdCard readEntity(Cursor cursor, int offset) {
        TestIdCard entity = new TestIdCard( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // cardId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // cardNo
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TestIdCard entity, int offset) {
        entity.setCardId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCardNo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TestIdCard entity, long rowId) {
        entity.setCardId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TestIdCard entity) {
        if(entity != null) {
            return entity.getCardId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TestIdCard entity) {
        return entity.getCardId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
