package com.baselibrary.dao.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.baselibrary.pojo.TestIdCard;

import com.baselibrary.pojo.TestPerson;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEST_PERSON".
*/
public class TestPersonDao extends AbstractDao<TestPerson, Long> {

    public static final String TABLENAME = "TEST_PERSON";

    /**
     * Properties of entity TestPerson.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property PersonId = new Property(0, Long.class, "personId", true, "_id");
        public final static Property PersonName = new Property(1, String.class, "personName", false, "PERSON_NAME");
    }

    private DaoSession daoSession;


    public TestPersonDao(DaoConfig config) {
        super(config);
    }
    
    public TestPersonDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEST_PERSON\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: personId
                "\"PERSON_NAME\" TEXT);"); // 1: personName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEST_PERSON\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TestPerson entity) {
        stmt.clearBindings();
 
        Long personId = entity.getPersonId();
        if (personId != null) {
            stmt.bindLong(1, personId);
        }
 
        String personName = entity.getPersonName();
        if (personName != null) {
            stmt.bindString(2, personName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TestPerson entity) {
        stmt.clearBindings();
 
        Long personId = entity.getPersonId();
        if (personId != null) {
            stmt.bindLong(1, personId);
        }
 
        String personName = entity.getPersonName();
        if (personName != null) {
            stmt.bindString(2, personName);
        }
    }

    @Override
    protected final void attachEntity(TestPerson entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TestPerson readEntity(Cursor cursor, int offset) {
        TestPerson entity = new TestPerson( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // personId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // personName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TestPerson entity, int offset) {
        entity.setPersonId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPersonName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TestPerson entity, long rowId) {
        entity.setPersonId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TestPerson entity) {
        if(entity != null) {
            return entity.getPersonId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TestPerson entity) {
        return entity.getPersonId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTestIdCardDao().getAllColumns());
            builder.append(" FROM TEST_PERSON T");
            builder.append(" LEFT JOIN TEST_ID_CARD T0 ON T.\"_id\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected TestPerson loadCurrentDeep(Cursor cursor, boolean lock) {
        TestPerson entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        TestIdCard testIdCard = loadCurrentOther(daoSession.getTestIdCardDao(), cursor, offset);
        entity.setTestIdCard(testIdCard);

        return entity;    
    }

    public TestPerson loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<TestPerson> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<TestPerson> list = new ArrayList<TestPerson>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<TestPerson> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<TestPerson> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
